runtime: python27
service: prodeo-eureka-app
threadsafe: true
handlers:
- url: /sw.js
  static_files: pwa/sw.js
  upload: pwa/ngsw-worker.js
  secure: always
  mime_type: application/javascript
  redirect_http_response_code: 301
- url: /(.*\.js)$
  static_files: pwa/\1
  upload: pwa/.*\.js$
  secure: always
  mime_type: application/javascript
  redirect_http_response_code: 301
- url: /(.*\.(css|map|png|jpg|svg|ico|json|txt|woff))$
  static_files: pwa/\1
  upload: pwa/.*\.(css|map|png|jpg|svg|ico|json|txt|woff)$
  secure: always
- url: /src/assets/images/(.*\.(css|map|png|jpg|svg|ico|json|txt|woff))$
  static_files: pwa/src/assets/images/\1
  upload: pwa/src/assets/images/.*\.(css|map|png|jpg|svg|ico|json|txt|woff)$
  secure: always
- url: '/(.*)'
  static_files: pwa/index.html
  upload: pwa/index.html
  secure: always
  redirect_http_response_code: 301